server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:file:~/shopdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true

  flyway:
    locations: classpath:/db/migration,classpath:/db/testdata

client:
  access-token-uri: http://localhost:8080/oauth/token
  id: shop-client
  grant.types: password,authorization_code,refresh_token,implicit
  authorities: CUSTOMER
  scopes: read,write,trust
  secret: secret
  token.validity:
    access: 3600
    refresh: 21600

ro:
  msg:
    shop:
      location-strategy: CLOSEST_LOCATION