server:
  port: 8080

security:
  oauth2:
    client:
      client-id: shop-client
      client-secret: secret
      access-token-uri: http://localhost:8081/oauth/token
      user-authorization-uri: http://localhost:8081/oauth/authorize
      clientAuthenticationScheme: form

    resource:
      user-info-uri: http://localhost:8081/user
