drop table if exists revenue;
create table revenue
(
  id          integer generated by default as identity,
  location_id integer,
  date        date,
  sum         decimal(19, 2),
  primary key (id)
);